use std::fs::{self, File};
use std::io::Write;
use std::path::Path;

fn main() {
    if let Err(e) = sync_version() {
        eprintln!("Failed to sync version: {}", e);
        std::process::exit(1);
    }

    if let Err(e) = generate_build_info() {
        eprintln!("Failed to generate build info: {}", e);
        std::process::exit(1);
    }

    tauri_build::build();
}

/// Sync the version from package.json into Cargo.toml.
fn sync_version() -> Result<(), String> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").map_err(|e| e.to_string())?;
    let package_json_path = Path::new(&manifest_dir).join("../package.json");
    let cargo_toml_path = Path::new(&manifest_dir).join("Cargo.toml");

    let package_contents = fs::read_to_string(&package_json_path)
        .map_err(|e| format!("Failed to read package.json: {}", e))?;
    let package_json: serde_json::Value = serde_json::from_str(&package_contents)
        .map_err(|e| format!("Failed to parse package.json: {}", e))?;
    let version = package_json
        .get("version")
        .and_then(|v| v.as_str())
        .ok_or("Version not found in package.json")?;

    let mut cargo_contents = fs::read_to_string(&cargo_toml_path)
        .map_err(|e| format!("Failed to read Cargo.toml: {}", e))?;

    let version_regex = regex::RegexBuilder::new(r#"^version = ".*"$"#)
        .multi_line(true)
        .build()
        .map_err(|e| format!("Regex error: {}", e))?;
    cargo_contents = version_regex
        .replace(&cargo_contents, format!(r#"version = "{}""#, version))
        .to_string();

    fs::write(&cargo_toml_path, &cargo_contents)
        .map_err(|e| format!("Failed to write Cargo.toml: {}", e))?;

    println!("Synced version {} to Cargo.toml", version);
    Ok(())
}

/// Generate app_build_info.rs in OUT_DIR from tauri.conf.json.
fn generate_build_info() -> Result<(), String> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").map_err(|e| e.to_string())?;
    let tauri_conf_path = Path::new(&manifest_dir).join("tauri.conf.json");
    let contents =
        fs::read_to_string(&tauri_conf_path).map_err(|e| format!("Read error: {}", e))?;

    let v: serde_json::Value =
        serde_json::from_str(&contents).map_err(|e| format!("JSON parse error: {}", e))?;

    let identifier = v
        .get("identifier")
        .and_then(|s| s.as_str())
        .unwrap_or("unknown.identifier");
    let product_name = v
        .get("productName")
        .and_then(|s| s.as_str())
        .unwrap_or("Unknown");
    let version = v.get("version").and_then(|s| s.as_str()).unwrap_or("0.0.0");

    let out_dir = std::env::var_os("OUT_DIR").ok_or_else(|| "OUT_DIR not set".to_string())?;
    let dest_path = Path::new(&out_dir).join("app_build_info.rs");
    let mut f = File::create(&dest_path).map_err(|e| format!("Create file error: {}", e))?;

    writeln!(f, "// Auto-generated by build.rs - do not edit").map_err(|e| e.to_string())?;
    writeln!(
        f,
        "#[allow(dead_code)] pub const APP_IDENTIFIER: &str = \"{}\";",
        identifier
    )
    .map_err(|e| e.to_string())?;
    writeln!(
        f,
        "#[allow(dead_code)] pub const APP_NAME: &str = \"{}\";",
        product_name
    )
    .map_err(|e| e.to_string())?;
    writeln!(
        f,
        "#[allow(dead_code)] pub const APP_VERSION: &str = \"{}\";",
        version
    )
    .map_err(|e| e.to_string())?;
    writeln!(
        f,
        "#[allow(dead_code)] pub const APP_IDENTIFIER_VERSION: &str = \"{}-{}\";",
        identifier, version
    )
    .map_err(|e| e.to_string())?;

    println!("cargo:rerun-if-changed={}", tauri_conf_path.display());
    Ok(())
}
